package: wortpresse
version: '0.2-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wortpresse


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"

page:
    title: translate:wortpresse_title
    prio: 11
    icon: rex-icon rex-icon-table
    block: system

pages:
    category:
        title: translate:wortpresse_category
        perm: wortpresse[category]
    taxonomy:
        title: translate:wortpresse_taxonomy
        perm: wortpresse[taxonomy]
    menu:
        title: translate:wortpresse_menu
        perm: wortpresse[menu]
    settings:
        title: translate:wortpresse_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    docs:
        title: translate:wortpresse_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: wortpresse[docs]

default_config:
    editor: 'class="form-control cke5-editor" data-lang="de" data-profile="default"'
