package: wortpresse
version: '0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wortpresse


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"



page:
    title: translate:wortpresse_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    wortpresse:
        title: translate:wortpresse_title

        block: system
        prio: 15
        icon: rex-icon fa-calendar
        perm: wortpresse[]
        subpages:
            table:
                title: translate:wortpresse_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            settings:
                title: translate:wortpresse_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:wortpresse_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: wortpresse[docs]

default_config:
    field: 'Test'
